export { default as Header } from './Header/Header'
export { default as ScrollingBar} from './Header/ScrollingBar'
export { default as Category } from './Header/Category'
export { default as Footer } from './Footer/Footer'
export { default as SideBar } from './SideBar/SideBar'
