export { default as ManageProduct } from "./Products/ManageProduct";
export { default as ManageUser } from "./Users/ManageUser";
export { default as ManageOrder } from "./Orders/ManageOrder";
export { default as SearchResults } from "./Products/Search";
export { default as Add } from "./Add";
export { default as Update } from "./Products/UpdateProduct";
export { default as UpdateUser } from "./Users/UpdateUser";
export { default as AddProduct } from "./Products/AddProduct";
export { default as Dashboard } from "./Dashboard";
